### ISSUE TITLE
Support for launch xib launch screen file?

### ISSUE THREAD

**Issue by sbhhbs** [IFTTT/IFTTTLaunchImage#2]

**Comment by jhersh** [comment]
Normally `-[UIViewController initWithNibName:bundle:]`requires that your nib file has (1) an owning view controller specified, and (2) a view outlet set. However, attempting to do so for a LaunchScreen file gives this error:

> Launch Screens may not have connections.

I would welcome a pull request here or comments from the community. This is not looking likely though. :(

**Comment by sbhhbs** [comment]
Try

```
    UINib *nib = [UINib nibWithNibName:@"LaunchScreen" bundle:nil];
    NSArray *arr = [nib instantiateWithOwner:nil options:nil];
    UIView *view = [arr firstObject];
```

**Comment by jhersh** [comment]
Thanks @sbhhbs, I think we are in business! Your thoughts on #3 ?
